# Generated by Django 4.2.7 on 2023-11-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="searchfield",
            field=models.TextField(blank=True),
        ),
    ]
