# Generated by Django 4.2.7 on 2023-11-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("begin", models.DateField()),
                ("end", models.DateField()),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "event",
            },
        ),
    ]
