# Generated by Django 4.2.7 on 2023-11-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="x",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="y",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
