# Generated by Django 4.2.7 on 2023-11-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_event_searchfield_event_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_name",
            new_name="name",
        ),
    ]
