# Generated by Django 4.2.7 on 2023-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_rename_event_name_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="kml",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="event",
            name="zoom",
            field=models.IntegerField(blank=True, default=11),
        ),
    ]
