# Generated by Django 4.2.7 on 2023-11-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0005_event_kml_event_zoom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="kml",
            field=models.URLField(blank=True),
        ),
    ]
