# Generated by Django 4.2.7 on 2023-11-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_alter_event_kml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="kml",
            field=models.TextField(blank=True),
        ),
    ]
