# Generated by Django 4.2.7 on 2023-11-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0008_alter_event_kml"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("small_map", models.ImageField(upload_to="")),
                (
                    "event_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="maps.event"
                    ),
                ),
            ],
        ),
    ]
