# Generated by Django 4.2.7 on 2023-11-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0009_localmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="localmap",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="localmap",
            name="x",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="localmap",
            name="y",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
